### ISSUE TITLE
Скорректировать интерфейсы страниц в соответствии с макетами в документе проектирования

### ISSUE THREAD

**Issue by ArsenChick** [ArsenChick/tuna-analyzer#22]
Разработать стили для следующих элементов:
- [x] -- верхняя панель:
  - [x] -- логотип
  - [x] -- кнопки
  - [x] -- отображение логина
- [x] -- страница регистрации
- [x] -- страница входа
- [ ] -- страница истории:
  - [ ] -- список записей 
  - [ ] -- запись
- [ ] -- страница анализатора:
  - [x] -- основная информация
  - [x] -- модальное окно подсказки
  - [ ] -- список записей 
  - [ ] -- запись
  - [x] -- полное название характеристики по наведению
- [x] не найденная страница

**Comment by JenkaCool** [comment]
Адаптировать элементы под мобильную версию:
- [] -- верхняя панель:
  - [] -- логотип
  - [] -- кнопки
  - [] -- отображение логина
- [] -- страница регистрации
- [] -- страница логина
- [ ] -- страница истории:
  - [ ] -- запись
  - [ ] -- панель воспроизведения
- [ ] -- страница анализатора:
  - [] -- основная информация
  - [] -- модальное окно подсказки
  - [ ] -- запись

**Comment by JenkaCool** [comment]
- [ ] добавить порядок табуляции
- [ ] скрывать историю, если нет записей
- [ ] полностью пробежаться по коду и исправить недочёты

**Comment by JenkaCool** [comment]
Возможно:
- [ ] прокрутка к результату анализа
- [ ] добавить порядок табуляции
